version: "3.8"

services: 

  nginx:
    container_name: "nginx"
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-1

  service-1:
    container_name: "service-1"
    image: mleongqa/service-1
    build: service_1
    environment:
      DATABASE_URI:
      SECRET_KEY:

  service-2:
    container_name: "service-2"
    image: mleongqa/service-2
    build: service_2/
  
  service-3:
    container_name: "service-3"
    image: mleongqa/service-3
    build: service_3/
  
  service-4:
    container_name: "service-4"
    image: mleongqa/service-4
    build: service_4/

  mysql:
    container_name: "mysql"
    image: mleongqa/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: