pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        SECRET_KEY = credentials("SECRET_KEY")
        DOCKERHUB_CREDENTIALS= credentials("DOCKERHUB_CREDENTIALS")
        MYSQL_DATABASE = credentials("MYSQL_DATABASE")
        MYSQL_ROOT_PASSWORD = credentials("MYSQL_ROOT_PASSWORD")
    }
    stages{
        stage("Install Dependencies"){
            steps{
                sh "bash scripts/setup.sh"
            }
        }
        stage("Test App"){
            steps{
                sh "bash scripts/test.sh"
            }
        }
        stage("Build Images"){
            steps{
                sh "bash scripts/build.sh"
            }
        }
        stage("Configure VMs"){
            steps{
                sh "bash scripts/config.sh"
            }
        }
        stage("Deploy Stack"){
            steps{
                sh "bash scripts/deploy.sh"
            }
        }
        stage("XML report"){
            steps{
                junit "junit.xml"
            }
        }
    }
}